export const MALE = 'male';
export const FEMALE = 'female';

export const actionTypes = {
  FILTER_BY_AUTHOR_GENDER: 'BOOKSFILTERS/FILTER_BY_AUTHOR_GENDER',
  FILTER_BY_BOOK_GENRE: 'BOOKSFILTERS/FILTER_BY_BOOK_GENRE',
  SORT_BY_BOOK_NAME: 'BOOKSFILTERS/SORT_BY_BOOK_NAME',
  SORT_BY_AUTHOR_NAME: 'BOOKSFILTERS/SORT_BY_AUTHOR_NAME'
};
