export const ROW_HEIGHT = 134;

export const actionTypes = {
  REQUEST: 'BOOKSLIST/REQUEST',
  SET_SORTING_STATUS: 'BOOKSLIST/SET_SORTING_STATUS',
  TRIGGER_FILTER: 'BOOKSLIST/TRIGGER_FILTER',
  BOOKS_CHUNK: 'BOOKSLIST/BOOKS_CHUNK',
  SUCCESS: 'BOOKSLIST/SUCCESS',
  FAILURE: 'BOOKSLIST/FAILURE',
}
